apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: lunch-spots-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lunch-spots-deploy
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
