apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: lunch-spots-networkpolicy
spec:
  podSelector:
    matchLabels:
      app: lunch-spots
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {}